### ISSUE TITLE
Remove the hamburger menu on the mobile privacy policy

### ISSUE THREAD

**Issue by zbreit** [bitcamp/bitcamp-site-2022#20]
Hi Faris! Great work on the privacy policy page--it looks really good! Much better than the PDF files that we've used in the past lol.

I did notice a small detail that I think we should address: the hamburger menu is still rendered on mobile even though there are no links.

![image](https://user-images.githubusercontent.com/6632788/157147057-ee88dd3d-f639-4eb6-bf70-fa845e43d87f.png)

We probably want to remove that hamburger menu from the HTML entirely.

**Comment by farisalipk** [comment]
Good catch, thanks! I’ll make that change right away
